### ISSUE TITLE
🐛 [Bug] Backend Exceeds Heap Size Limit and Restarts

### ISSUE THREAD

**Issue by Tirokk** [Human-Connection-Community/Human-Connection-New-20201003#2628]
> [<img alt="Tirokk" height="40" width="40" align="left" src="https://avatars1.githubusercontent.com/u/38261864?s=88&v=4">](https://github.com/Tirokk) **Authored by [Tirokk](https://github.com/Tirokk)**
_<time datetime="2019-12-29T10:38:44Z" title="Sunday, December 29th 2019, 11:38:44 am +01:00">Dec 29, 2019</time>_
_Closed <time datetime="2020-06-17T10:25:51Z" title="Wednesday, June 17th 2020, 12:25:51 pm +02:00">Jun 17, 2020</time>_
---

## :bug: Bugreport

Before Christmas the backend restarted every 5 minutes.

Matt and I have found that the heap size of the backend by default should be 1.5Gi.

It seems that we have to define:

```yaml
    spec:
      containers:
        resources:
          requests:
            memory: XXX
            cpu: XXX
          limits:
            memory: XXX
            cpu: XXX
```

And that should be done for the Neo4j database as well where only `requests. memory` was already defined.

See:
- https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/
- https://cloud.google.com/blog/products/gcp/kubernetes-best-practices-resource-requests-and-limits

### Steps to reproduce the behavior

Restarted 24 time since 21.12.2019 …
But does not since 25.12.2019 …

### Expected behavior

Should not restart by error.

### Additional context

Suggestions in VSCode are:

![Bildschirmfoto 2019-12-23 um 10 25 52](https://user-images.githubusercontent.com/25344101/71555790-f3c7ab80-2a2f-11ea-80d6-19e0b1fbcaef.png)

![Bildschirmfoto 2019-12-23 um 10 25 28](https://user-images.githubusercontent.com/25344101/71555795-00e49a80-2a30-11ea-9981-fa98b27b2c04.png)

May we have to set `requests` and `limits` for web app as well!?
